# NOTE: Used for both 6 and 7 dof bots. The joint_7 value will be unused for 6 dof bots
joint_1: 0.0
joint_2: -0.8650
joint_3: -3.15353
joint_4: -2.1302
joint_5: 0.00588
joint_6: -1.2077
joint_7: 1.5503
